version: '3.8'

services:
  sk_example_db:
    container_name: sk_example_db
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sk_example_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./src/main/resources/sk_example_db_data.sql:/docker-entrypoint-initdb.d/sk_example_db_data.sql
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  user_service:
    container_name: user_service
    image: app/serverside-developer-test:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    depends_on:
      sk_example_db:
        condition: service_healthy
    networks:
      - backend
networks:
  backend:
    driver: bridge
